-- this file is generated by program!
-- don't change it manaully.
-- source file: /Users/wangshaopei/Documents/work_sanguo/trunk_v3/tools/xls2lua/xls_flies/anis.xls

local anis = {
	[1]={
		{path1="face/face.plist",path2="face/face.png",sub_id=101,load_mode=1,name="bishi%d.png",time=300,amount_frames=2,scale=100},
		{sub_id=102,load_mode=1,name="liuhan%d.png",time=300,amount_frames=2,scale=100},
	},
}
return anis

