-- this file is generated by program!
-- don't change it manaully.
-- source file: /Users/wangshaopei/Documents/work_sanguo/trunk_v3/tools/xls2lua/xls_flies/formations.xls

local formations = {
	[1]={attr_type=1,add_percent=8,factor=0.2,level_open=0,level_up_interval=5},
	[2]={attr_type=1,add_percent=8,factor=0.2,level_open=0,level_up_interval=5},
	[3]={attr_type=2,add_percent=4,factor=0.16,level_open=5,level_up_interval=5},
	[4]={attr_type=2,add_percent=4,factor=0.16,level_open=5,level_up_interval=5},
	[5]={},
	[6]={attr_type=4,add_percent=4,factor=0.16,level_open=10,level_up_interval=5},
	[7]={attr_type=5,add_percent=8,factor=0.2,level_open=10,level_up_interval=5},
	[8]={attr_type=6,add_percent=4,factor=0.16,level_open=10,level_up_interval=5},
	[9]={},
	[10]={attr_type=3,add_percent=8,factor=0.2,level_open=10,level_up_interval=5},
}
return formations

