-- this file is generated by program!
-- don't change it manaully.
-- source file: /Users/wangshaopei/Documents/work_sanguo/trunk_v3/tools/xls2lua/xls_flies/builds.xls

local science = {
	[1001]={attr_type=1,base_val=10,factor=0.4,level_open=0,level_up_interval=2},
	[1002]={attr_type=2,base_val=8,factor=0.16,level_open=0,level_up_interval=2},
	[1003]={attr_type=3,base_val=10,factor=0.4,level_open=0,level_up_interval=2},
	[1004]={attr_type=4,base_val=8,factor=0.16,level_open=0,level_up_interval=2},
	[1005]={attr_type=5,base_val=10,factor=0.4,level_open=0,level_up_interval=2},
	[1006]={attr_type=6,base_val=8,factor=0.16,level_open=0,level_up_interval=2},
	[1007]={attr_type=7,base_val=50,factor=0.5,level_open=0,level_up_interval=2},
}
return science

