-- this file is generated by program!
-- don't change it manaully.
-- source file: F:\ProjectX\code\trunk\tools\xls2lua/xls_flies/mission.xls

local mission = {
	[1]={name="关卡任务",desc="通关%d次关卡",type=0,lv=1,auto=false,complete={1,101,3},item={20101000,1,20102000,1}},
	[2]={name="收集物品任务",desc="收集%s物品%d个",type=0,lv=1,auto=false,complete={2,20101000,1},renown=10},
	[3]={name="使用物品",desc="使用%s物品",type=0,lv=1,auto=false,complete={3,20101000,1},forage=10},
	[4]={name="武将招募",desc="武将招募",type=0,lv=1,auto=false,complete={4,1001,1}},
	[5]={name="武将解锁数量",desc="武将解锁数量",type=0,lv=1,auto=false,complete={5,1001,1}},
	[6]={name="武将品质",desc="武将品质",type=0,lv=1,auto=false,complete={6,2,2}},
	[7]={name="武将等级",desc="武将等级",type=0,lv=1,auto=false,complete={7,2,2}},
	[8]={name="兵种等级",desc="兵种等级",type=0,lv=1,auto=false,complete={8,2,2}},
	[9]={name="装备等级",desc="装备等级",type=0,lv=1,auto=false,complete={9,2,2}},
	[10]={name="装备品质",desc="装备品质",type=0,lv=1,auto=false,complete={10,2,2}},
	[11]={name="装备星级",desc="装备星级",type=0,lv=1,auto=false,complete={11,2,2}},
	[12]={name="宝石等级",desc="宝石等级",type=0,lv=1,auto=false,complete={12,2,2}},
	[13]={name="好友数量",desc="好友数量",type=0,lv=1,auto=false,complete={13,2}},
	[14]={name="声望",desc="声望",type=0,lv=1,auto=false,complete={14,100}},
	[15]={name="擂台排名",desc="擂台排名",type=0,lv=1,auto=false,complete={14,1000}},
	[16]={name="在线时长",desc="在线%s",type=0,lv=1,auto=false,complete={16,3},money=100},
}
return mission

