-- this file is generated by program!
-- don't change it manaully.
-- source file: F:\ProjectX\code\trunk\tools\xls2lua/xls_flies/mission.xls

local stroy = {
	[1]={next=2,pos=0,desc="剧情开始"},
	[2]={pos=0,desc="剧情结束"},
}
return stroy

